[package]
name = "advent_of_code_2025"
version = "0.1.0"
edition = "2021"

[dependencies]

[[bin]]
name = "day_1"
path = "src/bin/day1.rs"

[[bin]]
name = "day_2"
path = "src/bin/day2.rs"

[[bin]]
name = "day_3"
path = "src/bin/day3.rs"
